In [2]:
!pip install requests
!pip install beautifulsoup4
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests) (2025.11.12)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: beautifulsoup4 in c:\programdata\anaconda3\lib\site-packages (4.13.5)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4) (4.15.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

print("Libraries installed successfully")

Libraries installed successfully

In [4]:
url = "http://books.toscrape.com/"

response = requests.get(url)

print(response.status_code)

200

In [5]:
soup = BeautifulSoup(response.text, "html.parser")

print("Website loaded successfully")

Website loaded successfully

In [6]:
books = soup.find_all("article", class_="product_pod")

print(len(books))

20

In [7]:
book_names = []
prices = []
ratings = []

In [8]:
for book in books:
    
    name = book.h3.a["title"]
    price = book.find("p", class_="price_color").text
    rating = book.p["class"][1]
    
    book_names.append(name)
    prices.append(price)
    ratings.append(rating)

In [9]:
print(book_names[:5])

['A Light in the Attic', 'Tipping the Velvet', 'Soumission', 'Sharp Objects', 'Sapiens: A Brief History of Humankind']

In [10]:
df = pd.DataFrame({
    "Book Name": book_names,
    "Price": prices,
    "Rating": ratings
})

In [11]:
df.head()

                               Book Name    Price Rating
0                   A Light in the Attic  Â£51.77  Three
1                     Tipping the Velvet  Â£53.74    One
2                             Soumission  Â£50.10    One
3                          Sharp Objects  Â£47.82   Four
4  Sapiens: A Brief History of Humankind  Â£54.23   Five

In [12]:
df.to_csv("books_data.csv", index=False)

print("CSV file saved successfully")

CSV file saved successfully

In [13]:
df.shape

(20, 3)

In [16]:
 df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Book Name  20 non-null     object
 1   Price      20 non-null     object
 2   Rating     20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes

In [17]:
df.describe(include='all')

                   Book Name    Price Rating
count                     20       20     20
unique                    20       20      5
top     A Light in the Attic  Â£51.77    One
freq                       1        1      6